/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.sgli.Presentation;

import br.edu.ifnmg.tads.sgli.DataAccess.CaixaDAO;
import br.edu.ifnmg.tads.sgli.DataAccess.SessaoDAO;
import br.edu.ifnmg.tads.sgli.DataAccess.UsuarioDAO;
import br.edu.ifnmg.tads.sgli.DomainModel.Caixa;
import br.edu.ifnmg.tads.sgli.DomainModel.Funcionario;
import br.edu.ifnmg.tads.sgli.DomainModel.Sessao;
import br.edu.ifnmg.tads.sgli.DomainModel.Usuario;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diego
 */
public class frmPrincipal extends javax.swing.JFrame {

    UsuarioDAO usuarioDAO = new UsuarioDAO();
    Usuario usuario;
    CaixaDAO caixaDAO = new CaixaDAO();
    Caixa caixa = new Caixa();
    Funcionario funcionario;
    Sessao sessao;
    SessaoDAO sessaoDAO;
    
    
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(Funcionario funcionario) {
        initComponents();
        this.funcionario = funcionario;
        lblNomeUsuario.setText(this.funcionario.getNome());
        carregaSessao(funcionario);
    }
    
    private void carregaSessao(Funcionario funcionario) {
        Date data = new Date();
        try {
            sessao = new Sessao();
            sessaoDAO = new SessaoDAO();
            caixa = caixaDAO.AbrirCaixa(1);

            sessao.setDataInicio(data);
            sessao.setUsuario(usuarioDAO.AbrirUsuario(funcionario.getCodigo()));
            sessao.setCaixa(caixa);
            sessao.setSaldoAbertura(caixa.getSaldo());

            sessaoDAO.Salvar(sessao);
        } catch (Exception ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuControle = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        Ferramentas = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuiLogoff = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        imnuCadastroClientes = new javax.swing.JMenuItem();
        imnuCadastroFuncionarios = new javax.swing.JMenuItem();
        imnuCadastroFornecedores = new javax.swing.JMenuItem();
        imnuUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        imnuCadastroCargos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        imnuCadastoProdutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        imnuCadastroGrupoProdutos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        imnuVenda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGLI - Sistema Loja de Informática");

        lblNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");

        mnuControle.setText("Controle");

        jMenuItem3.setText("Estatística de Caixa");
        mnuControle.add(jMenuItem3);
        mnuControle.add(jSeparator1);

        jMenuItem4.setText("Trocar de Funcionário");
        mnuControle.add(jMenuItem4);

        Ferramentas.setText("Ferramentas");
        mnuControle.add(Ferramentas);

        jMenuItem6.setText("Fechar");
        mnuControle.add(jMenuItem6);

        mnuiLogoff.setText("Logoff");
        mnuiLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiLogoffActionPerformed(evt);
            }
        });
        mnuControle.add(mnuiLogoff);

        jMenuBar1.add(mnuControle);

        jMenu3.setText("Cadastro");

        imnuCadastroClientes.setText("Cadastro de Clientes");
        imnuCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuCadastroClientesActionPerformed(evt);
            }
        });
        jMenu3.add(imnuCadastroClientes);

        imnuCadastroFuncionarios.setText("Cadastro de Funcionários");
        imnuCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuCadastroFuncionariosActionPerformed(evt);
            }
        });
        jMenu3.add(imnuCadastroFuncionarios);

        imnuCadastroFornecedores.setText("Cadastro de Fornecedores");
        imnuCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuCadastroFornecedoresActionPerformed(evt);
            }
        });
        jMenu3.add(imnuCadastroFornecedores);

        imnuUsuario.setText("Cadastrar Usuarios");
        imnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(imnuUsuario);
        jMenu3.add(jSeparator2);

        imnuCadastroCargos.setText("Cadastro de Cargos");
        imnuCadastroCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuCadastroCargosActionPerformed(evt);
            }
        });
        jMenu3.add(imnuCadastroCargos);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Produtos");

        imnuCadastoProdutos.setText("Cadastrar Produtos");
        imnuCadastoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuCadastoProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(imnuCadastoProdutos);

        jMenuItem1.setText("Cadastrar Marcas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        imnuCadastroGrupoProdutos.setText("Cadastro de Grupo de Produtos");
        imnuCadastroGrupoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuCadastroGrupoProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(imnuCadastroGrupoProdutos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vendas");

        imnuVenda.setText("Venda");
        imnuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnuVendaActionPerformed(evt);
            }
        });
        jMenu2.add(imnuVenda);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Relatórios");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(442, 442, 442)
                    .addComponent(lblUsuario)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblUsuario)
                        .addComponent(lblNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(134, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imnuCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuCadastroClientesActionPerformed
        frmClienteListagem janela = new frmClienteListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_imnuCadastroClientesActionPerformed

    private void imnuCadastroGrupoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuCadastroGrupoProdutosActionPerformed
        frmGrupoProdutosListagem janela = new frmGrupoProdutosListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_imnuCadastroGrupoProdutosActionPerformed

    private void imnuCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuCadastroFuncionariosActionPerformed
        frmFuncionarioListagem janela = new frmFuncionarioListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_imnuCadastroFuncionariosActionPerformed

    private void imnuCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuCadastroFornecedoresActionPerformed
        frmFornecedorListagem janela = new frmFornecedorListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_imnuCadastroFornecedoresActionPerformed

    private void imnuCadastroCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuCadastroCargosActionPerformed
        frmCargoListagem janela = new frmCargoListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_imnuCadastroCargosActionPerformed

    private void imnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuUsuarioActionPerformed
        
    }//GEN-LAST:event_imnuUsuarioActionPerformed

    private void imnuCadastoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuCadastoProdutosActionPerformed
        frmProdutoListagem janela = new frmProdutoListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_imnuCadastoProdutosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmMarcaListagem janela = new frmMarcaListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void imnuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnuVendaActionPerformed
        frmVenda janela = new frmVenda(funcionario,sessao);
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_imnuVendaActionPerformed

    private void mnuiLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiLogoffActionPerformed
        logoff();
    }//GEN-LAST:event_mnuiLogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ferramentas;
    private javax.swing.JMenuItem imnuCadastoProdutos;
    private javax.swing.JMenuItem imnuCadastroCargos;
    private javax.swing.JMenuItem imnuCadastroClientes;
    private javax.swing.JMenuItem imnuCadastroFornecedores;
    private javax.swing.JMenuItem imnuCadastroFuncionarios;
    private javax.swing.JMenuItem imnuCadastroGrupoProdutos;
    private javax.swing.JMenuItem imnuUsuario;
    private javax.swing.JMenuItem imnuVenda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu mnuControle;
    private javax.swing.JMenuItem mnuiLogoff;
    // End of variables declaration//GEN-END:variables

   protected void logoff() {
        Date data = new Date();
        try {
            caixa = caixaDAO.AbrirCaixa(1);
            sessao.setDataTermino(data);
            sessao.setSaldoFechamento(caixa.getSaldo());
            sessaoDAO.Salvar(sessao);


            frmLogin janela = new frmLogin();

            janela.setVisible(true);
            setVisible(false);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}





